config/routes.rb
Rails.application.routes.draw do
  # mount ActionCable.server, at: '/cable'
  root 'customers#lookup'

  get 'lookup', to: 'customers#lookup'
  get 'customers/export_attendance', to: 'customers#export_attendance'
  get 'admin', to: 'static_pages#admin'
  get 'dashboard', to: 'static_pages#dashboard'
  get 'setup', to: 'static_pages#setup'

  resources :employees
  resources :customers do
    collection do
      post :import
      post :import_reg
      get :rsvp
      get :checked_in
    end
  end
  get 'reset/check_ins', to: 'actions#reset_check_ins'
  get 'reset/registrations', to: 'actions#reset_registrations'
  get 'reset/database', to: 'actions#reset_database'

  resources :sessions, only: [:new, :create, :destroy]

  resources :settings

  get 'login', to: 'static_pages#home'
  get 'logout', to: 'sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authorized, only: [:admin]

  def home
    @customers = Customer.all
    @employee = Employee.new
  end

  def admin
    @customer = Customer.new
    @employee = Employee.new

    @employees = Employee.all
  end
  def dashboard
    @recent_checkins = Customer.filter_by_checked_in(true).order(updated_at: :desc).limit(20)
    render layout: 'dashboard'
  end

  def setup
    render layout: 'dashboard'
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_actions_modal.html.erb
<h4>Actions</h4>
<hr>
<p>The below actions are NOT REVERSIBLE. Please exercise extreme caution when performing the actions below. No backups exist for the data and data during the event cannot be recovered.</p>
<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#confirmResetCheckIns">
    Reset Check-Ins
</button>
<br>
<br>
<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#confirmResetRegistrations">
    Reset Registrations
</button>
<br>
<br>
<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#confirmResetDatabase">
    Reset Customer Database
</button>

<div class="modal fade" id="confirmResetCheckIns" tabindex="-1" aria-labelledby="confirmResetCheckIns" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="confirmResetCheckIns">Danger!</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        This action will reset all current check-ins. Are you sure you want to continue?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
        <%= link_to "Yes", reset_check_ins_path, class:"btn btn-danger" %>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="confirmResetRegistrations" tabindex="-1" aria-labelledby="confirmResetRegistrations" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="confirmResetCheckIns">Danger!</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        This action will reset all registrations. Are you sure you want to continue?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
        <%= link_to "Yes", reset_registrations_path, class:"btn btn-danger" %>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="confirmResetDatabase" tabindex="-1" aria-labelledby="confirmResetDatabase" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="confirmResetDatabase">Danger!</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        This action will reset the customer database. All customers will be removed. Are you sure you want to continue?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
        <%= link_to "Yes", reset_database_path, class:"btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_export_attendance_modal.html.erb
<h4>Export Attendance</h4>
<hr>
Click the link below to export attendance for the event. The file will be a CSV file. This will not export all records, just the individuals who attended the event. <br><br>
<%= link_to "Export Attendance", {controller: "customers", action: "export_attendance", format:"csv"}, class:"btn btn-primary" %>

app/views/static_pages/_helpful_links_modal.html.erb
<h4>Helpful Links</h4>
<hr>
<p>Below are a few helpful links to help monitor activity during the event. These links will open in new tabs.</p>
<%= link_to "Live Dashboard", dashboard_path, class:"nav-link", target: :_blank %>
<%= link_to "Customer Preview", customers_path, class:"nav-link", target: :_blank %>
<%= link_to "RSVP'ed Customers", rsvp_customers_path, class:"nav-link", target: :_blank %>
<%= link_to "Checked-In Customers", checked_in_customers_path, class:"nav-link", target: :_blank %>
<%= link_to "Portainer Dashboard", "http://#{request.host}:9000", class:"nav-link", target: :_blank %>

app/views/static_pages/_new_customer_modal.html.erb
<h4>Create Customer</h4>
<hr>
Fill out the form below to create a new customer.<br><br>
<%= form_with(model: customer) do |form| %>
<div class="row">
<div class="col-6">
<label class="form-label">Customer Number:</label>
<%= form.text_field :customer_number, class:"form-control" %>
</div>
<div class="col-6">
<label class="form-label">Full Name:</label>
<%= form.text_field :name, class:"form-control" %>
</div>
<div class="col-6">
<label class="form-label">Phone Number:</label>
<%= form.text_field :phone_number, class:"form-control" %>
</div>
<div class="col-6">
<label class="form-label">CO:</label>
<%= form.text_field :co, class:"form-control" %>
</div>
<div class="col-6">
<label class="form-label">Mailing Address:</label>
<%= form.text_field :address, class:"form-control" %>
</div>
<div class="col-6">
<label class="form-label">Physical Address:</label>
<%= form.text_field :phys_address, class:"form-control" %>
</div>
<div class="col-6">
<label class="form-label">Employee / Director:</label>
<%= form.select(:empdir, [['Employee','E'],['Director','D']],{}, { :class => 'form-control'}) %>
</div>
<div class="col-6">
<label class="form-label">Dinner Count:</label>
<%= form.number_field :actual_dinner_count, class:"form-control" %>
</div>
<div class="col-6">

<%= form.check_box :registered, class:"form-check-input" %>
<label class="form-label">Registered</label>
</div>
<div class="col-6">

<%= form.check_box :checked_in, class:"form-check-input" %>
<label class="form-label">Checked-In</label>
</div>
<div class="col-6">

<%= form.check_box :registered_at_event, class:"form-check-input" %>
<label class="form-label">Registered at Event</label>
</div>
<div class="col-6">

<%= form.check_box :voted, class:"form-check-input" %>
<label class="form-label">Voted</label>
</div>
<div class="col-6">

<%= submit_tag "Create Customer", class:"btn btn-primary" %>
</div>
</div>
<% end %>

app/views/static_pages/_new_employee_modal.html.erb
<h4>Create Employee</h4>
<hr>
Fill out the form below to create a new employee.<br><br>
<%= form_with(model: employee) do |form| %>
<div class="row">
  <div class="col-6">
    <label class="form-label">First Name:</label>
    <%= form.text_field :first_name, class:"form-control" %>
  </div>
  <div class="col-6">
    <label class="form-label">Last Name:</label>
    <%= form.text_field :last_name, class:"form-control" %>
  </div>
  <div class="col-6">
    <label class="form-label">PIN:</label>
    <%= form.text_field :PIN, class:"form-control" %>
  </div>
  <div class="col-6">
    <br>
    <%= form.check_box :is_admin, class:"form-check-input" %>
    <label class="form-check-label">Admin</label>
  </div>
  <div class="col-6">
    <br>
    <%= submit_tag "Create Employee", class:"btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/static_pages/_recent_checkins_modal.html.erb
<table class="table" id="recent_table">
  <thead>
    <tr>
      <th scope="col">Customer Number</th>
      <th scope="col">Name</th>
      <th scope="col">Address</th>
      <th scope="col">Dinner Count</th>
      <th scope="col">Registered at Event</th>
    </tr>
  </thead>
  <tbody>
    <% @recent_checkins.each do |customer| %>
      <tr>
        <td><%= customer.customer_number %></td>
        <td><%= customer.name %></td>
        <td><%= customer.address %></td>
        <td><%= customer.actual_dinner_count %></td>
        <td><% if customer.registered_at_event %>Yes<% else %>No<% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/static_pages/_settings_modal.html.erb
<h4>Settings</h4>
<hr>
<%= form_for(Setting.new, url: settings_path) do |f| %>
    <label for="event_name" class="form-label">Event Name</label>
    <%= f.text_field :event_name, value: Setting.event_name, class:"form-control" %>
    <br>
    <label for="purchased_meal_count" class="form-label">Purchased Meal Count</label>
    <%= f.number_field :purchased_meal_count, value: Setting.purchased_meal_count, class:"form-control" %>
    <br>
    <label for="instance_name" class="form-label">Instance Name</label>
    <%= f.text_field :instance_name, value: Setting.instance_name, class:"form-control" %>
    <br>
    <%= f.check_box :delete_enabled, class:"form-check-input" %>
    <label for="delete_enabled" class="form-label">Enable Deletion of Customers</label>
    <br>
    <br>
    <%= f.submit "Save", class:"btn btn-primary" %>
<% end %>

app/views/static_pages/_upload_customers_modal.html.erb
<h4>Import Customers</h4>
<hr>
<p>Import the list of customers below. The import file should be a CSV. The CSV should be a standard comma delimated file including a header. Below are the allowed fields and their descriptions:</p>
<dl class="row">
  <dt class="col-sm-3"><code>customer_number</code></dt>
  <dd class="col-sm-9">Must be unique. Maps to the Account number and is the same field typically used for the star code. Cannot be blank.</dt>
  <dt class="col-sm-3"><code>name</code></dt>
  <dd class="col-sm-9">The customer's full name. Cannot be blank.</dt>
  <dt class="col-sm-3"><code>address</code></dt>
  <dd class="col-sm-9">The customer's mailing address. Typically maps to the Address 1 field in the customer excel document.</dt>
  <dt class="col-sm-3"><code>phys_address</code></dt>
  <dd class="col-sm-9">The customer's physical, or service, address.</dt>
  <dt class="col-sm-3"><code>phone_number</code></dt>
  <dd class="col-sm-9">The customer's phone number. The system will automatically format the phone number, no need to add brackets or hyphens.</dt>
  <dt class="col-sm-3"><code>co</code></dt>
  <dd class="col-sm-9">The CO that services the customer. Not required.</dt>
  <dt class="col-sm-3"><code>empdir</code></dt>
  <dd class="col-sm-9">Indicates whether the customer is also an employee or director. Can only specify one or the other. For an employee, indicate with an "E" in the field and for a director, use a "D" (no quotes).</dt>
  <dt class="col-sm-3"><code>member_number</code></dt>
  <dd class="col-sm-9">The member number for the customer, helpful for the service desk to find the customer. Not required.</dt>
</dl>
<%= form_tag import_customers_path, multipart:true do %>
  <%= file_field_tag :file, class:"form-control" %>
  <br>
  <%= submit_tag "Import CSV", class:"btn btn-primary" %>
<% end %>

app/views/static_pages/_upload_registrations_modal.html.erb
<h4>Upload Registrations</h4>
<hr>
<p>Import the registrations below. The import file should be a CSV. The CSV should be a standard comma delimated file including a header. The below fields are allowed:</p>
<dl class="row">
  <dt class="col-sm-3"><code>customer_number</code></dt>
  <dd class="col-sm-9">Links to the customer and is typically referred to as the Account number. This is also the field used for the star codes. This is required.</dd>
  <dt class="col-sm-3"><code>dinner_count</code></dt>
  <dd class="col-sm-9">The number of meal tickets the customer registered for. Does not need to be filled in, but does need to be a number if it is.</dd>
  <dt class="col-sm-3"><code>registered</code></dt>
  <dd class="col-sm-9">Boolean field indicating whether or not the customer registered to come to the Annual Meeting.</dd>
  <dt class="col-sm-3"><code>voted</code></dt>
  <dd class="col-sm-9">Boolean field indicating whether or not the customer voted on the online registration portal.</dd>
</dl>
<%= form_tag import_reg_customers_path, multipart:true do %>
  <%= file_field_tag :file, class:"form-control" %>
  <br>
  <%= submit_tag "Import CSV", class:"btn btn-primary" %>
<% end %>

app/views/static_pages/_view_employees_modal.html.erb
<h4>Employee Accounts</h4>
<hr>
<table class="table">
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">PIN</th>
      <th scope="col">Admin</th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.PIN %></td>
        <td><% if employee.is_admin %><span class="badge bg-success">Yes</span><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/static_pages/admin.html.erb
<div class="row justify-content-center">
  <div class="col-9">
    <h1 class="display-6">Admin Dashboard</h1>
      <% if notice %>
      <br>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      <% end %>
      <% if flash[:error] %>
      <br>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= flash[:error] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      <% end %>
    <br>
    <div class="card">
      <div class="card-body">
        <div class="d-flex align-items-start">
          <ul class="nav flex-column col-3 nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <li class="nav-item">
              <a href="#" class="nav-link active" id="v-pills-settings-tab" data-bs-toggle="pill" data-bs-target="#v-pills-settings" type="button" role="tab" aria-controlls="v-pills-settings" aria-selected="true">Settings</a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link" id="v-pills-import-customers-tab" data-bs-toggle="pill" data-bs-target="#v-pills-import-customers" type="button" role="tab" aria-controlls="v-pills-import-customers" aria-selected="false">Import Customers</a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link" id="v-pills-upload-registrations-tab" data-bs-toggle="pill" data-bs-target="#v-pills-upload-registrations" type="button" role="tab" aria-controlls="v-pills-upload-registrations" aria-selected="false">Upload Registrations</a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link" id="v-pills-export-attendance-tab" data-bs-toggle="pill" data-bs-target="#v-pills-export-attendance" type="button" role="tab" aria-controlls="v-pills-export-attendance" aria-selected="false">Export Attendance</a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link" id="v-pills-new-customer-tab" data-bs-toggle="pill" data-bs-target="#v-pills-new-customer" type="button" role="tab" aria-controlls="v-pills-new-customer" aria-selected="false">Create Customer</a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link" id="v-pills-view-employees-tab" data-bs-toggle="pill" data-bs-target="#v-pills-view-employees" type="button" role="tab" aria-controlls="v-pills-view-employees" aria-selected="false">View Employees</a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link" id="v-pills-create-employee-tab" data-bs-toggle="pill" data-bs-target="#v-pills-create-employee" type="button" role="tab" aria-controlls="v-pills-create-employee" aria-selected="false">Create Employee</a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link" id="v-pills-actions-tab" data-bs-toggle="pill" data-bs-target="#v-pills-actions" type="button" role="tab" aria-controlls="v-pills-actions" aria-selected="false">Actions</a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link" id="v-pills-actions-tab" data-bs-toggle="pill" data-bs-target="#v-pills-helpful-links" type="button" role="tab" aria-controlls="v-pills-helpful-links" aria-selected="false">Helpful Links</a>
            </li>
          </ul>
          <div class="col-1">
          </div>
          <div class="col-8">
            <div class="tab-content" id="v-pills-tabContent">
              <div class="tab-pane show active" id="v-pills-settings" role="tabpanel" aria-labeledby="v-pills-settings-tab" tabindex="0"><%= render "static_pages/settings_modal" %></div>
              <div class="tab-pane" id="v-pills-import-customers" role="tabpanel" aria-labeledby="v-pills-import-customers-tab" tabindex="0"><%= render "static_pages/upload_customers_modal" %></div>
              <div class="tab-pane" id="v-pills-upload-registrations" role="tabpanel" aria-labeledby="v-pills-upload-registrations-tab" tabindex="0"><%= render "static_pages/upload_registrations_modal" %></div>
              <div class="tab-pane" id="v-pills-export-attendance" role="tabpanel" aria-labeledby="v-pills-export-attendance-tab" tabindex="0"><%= render "static_pages/export_attendance_modal" %></div>
              <div class="tab-pane" id="v-pills-new-customer" role="tabpanel" aria-labeledby="v-pills-new-customer-tab" tabindex="0"><%= render "static_pages/new_customer_modal", customer: @customer %></div>
              <div class="tab-pane" id="v-pills-view-employees" role="tabpanel" aria-labeledby="v-pills-view-employees-tab" tabindex="0"><%= render "static_pages/view_employees_modal" %></div>
              <div class="tab-pane" id="v-pills-create-employee" role="tabpanel" aria-labeledby="v-pills-create-employee-tab" tabindex="0"><%= render "static_pages/new_employee_modal", employee: @employee %></div>
              <div class="tab-pane" id="v-pills-actions" role="tabpanel" aria-labeledby="v-pills-actions-tab" tabindex="0"><%= render "static_pages/actions_modal" %></div>
              <div class="tab-pane" id="v-pills-helpful-links" role="tabpanel" aria-labeledby="v-pills-helpful-links-tab" tabindex="0"><%= render "static_pages/helpful_links_modal" %></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<br>
<br>

app/views/static_pages/dashboard.html.erb
<div class="col-12">
    <div class="row">
    <div class="col-3 p-3">
        <div class="card">
        <h5 class="card-header">Total RSVPs</h5>
        <div class="card-body">
            <h1 id="stat_rsvp"><%= total_rsvp %></h1>
        </div>
        </div>
    </div>
    <div class="col-3 p-3">
        <div class="card">
        <h5 class="card-header">Total Checked-In Customers</h5>
        <div class="card-body">
            <h1 id="stat_checked_in"><%= total_checkins %></h1>
        </div>
        </div>
    </div>
    <div class="col-3 p-3">
        <div class="card">
        <h5 class="card-header">Total Walk-Ins</h5>
        <div class="card-body">
            <h1 id="stat_walk_ins"><%= total_walkins %></h1>
        </div>
        </div>
    </div>
    <div class="col-3 p-3">
        <div class="card">
        <h5 class="card-header">Checked-In Percentage</h5>
        <div class="card-body">
            <h1 id="stat_percentage"><%= checked_in_percentage %>%</h1>
        </div>
        </div>
    </div>
    </div>
</div>
<br>
<div class="clearfix">
  <div class="row clearfix">
    <div class="col-12">
      <h4>Recent Check-Ins:</h4>
      <% if total_checkins > 0 %>
        <%= render "static_pages/recent_checkins_modal" %>
      <% else %>
        <h6>No customers have checked-in yet!</h5>
      <% end %>
    </div>
  </div>
</div>
<br><br>

app/views/static_pages/home.html.erb
<div class="row justify-content-center">
  <div class="col-8">
    <h1 class="display-6 text-center">Event Check-In</h1>
  </div>
</div>
<br>
<div class="row justify-content-center align-items-center">
  <div class="col-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Please input your employee code below to continue.</h5><br>
        <%= form_with url: sessions_path do |form| %>
          <div class="form-group mb-3">
            <%= form.text_field :PIN, class:"form-control form-control-lg" %>
          </div>
          <div class="d-grid gap-2">
            <%= form.submit "Login", class:"btn btn-lg btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div
</div>

app/views/static_pages/setup.html.erb
<div class="row justify-content-center">
  <div class="col-8">
    <h1 class="display-6 text-center"></h1>
  </div>
</div>
<br>
<div class="clearfix">
  <div class="row justify-content-center align-items-center">
    <div class="col-8">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">First Launch</h5><br>
          <p class="card-text">This appears to be the first time that this application has been started. To login, click the login button in the lower right-hand corner. The default PIN code is 313131. After you are logged in, you can click the Admin button in the lower left-hand corner to change the settings for the event. In the admin panel, you can also upload the list of customers and registrations.</p>
          <p class="card-text">Additionally, as part of the image for this web application, a Portainer instance has been setup to help manage the containers. The username is <code>admin</code> and the password is <code><%= ENV["PORTAINER_PW"] %></code>. You can access the management interface by clicking <%= link_to "here", "http://#{request.host}:9000", target: :_blank %>.</p>
          <p class="card-text">Clicking Continue below will clear this message, so please note the PIN before doing so. The Portainer credentials are stored in LastPass.</p>
        </div>
        <div class="card-footer">
            <%= form_for(Setting.new, url: settings_path) do |f| %>
                <%= f.hidden_field :first_launch, value: false %>
                <%= f.submit "Continue", class:"btn btn-danger float-end" %>
            <% end %>
        </div>
      </div>
    </div
  </div>
</div>