config/routes.rb
Rails.application.routes.draw do
  # mount ActionCable.server, at: '/cable'
  root 'customers#lookup'

  get 'lookup', to: 'customers#lookup'
  get 'customers/export_attendance', to: 'customers#export_attendance'
  get 'admin', to: 'static_pages#admin'
  get 'dashboard', to: 'static_pages#dashboard'
  get 'setup', to: 'static_pages#setup'

  resources :employees
  resources :customers do
    collection do
      post :import
      post :import_reg
      get :rsvp
      get :checked_in
    end
  end
  get 'reset/check_ins', to: 'actions#reset_check_ins'
  get 'reset/registrations', to: 'actions#reset_registrations'
  get 'reset/database', to: 'actions#reset_database'

  resources :sessions, only: [:new, :create, :destroy]

  resources :settings

  get 'login', to: 'static_pages#home'
  get 'logout', to: 'sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :customer_number, presence: true
  scope :filter_by_checked_in, -> (checked_in) {where checked_in: checked_in}
  scope :filter_by_registered_at_event, -> (registered_at_event) {where registered_at_event: registered_at_event}
  scope :filter_by_rsvp, -> (rsvp) {where registered: rsvp}
  
  attr_accessor :is_employee, :is_director

  require 'csv'

  def self.search(search)
    if search
      customers = Customer.where("customer_number = ? OR phys_address LIKE '#{search} %'", search)
    else
      customers = Customer.all.limit(200)
    end
    return customers
  end

  def self.to_csv
    attributes = %w{customer_number co name phys_address dinner_count actual_dinner_count registered_at_event voted}
    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |customer|
        csv << attributes.map{ |attr| customer.send(attr)}
      end
    end
  end

  def is_employee
    if self[:empdir]
      if self[:empdir].include? "E"
        return true
      else
        return false
      end
    else
      return false
    end
  end

  def is_director
    if self[:empdir]
      if self[:empdir].include? "D"
        return true
      else
        return false
      end
    else
      return false
    end
  end

  def is_vip
    if self[:empdir]
      if self[:empdir].include? "V"
        return true
      else
        return false
      end
    else
      return false
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]
  before_action :authorized, only: %i[ new edit import import_reg export_attendance create destroy]
  require 'csv'

  # GET /customers or /customers.json
  def index
    @customers = Customer.search(params[:search])
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  def rsvp
    @customers = Customer.filter_by_rsvp(true).filter_by_checked_in(nil)
  end

  def checked_in
    @customers = Customer.filter_by_checked_in(true)
  end

  def lookup
      if Setting.first_launch
        redirect_to setup_url
      end
      if turbo_frame_request?
        @customers = Customer.search(params[:search])
        render partial: "customers", locals: { customers: @customers }
      end
  end

  # POST /customers/import
  def import
    customers = []
    CSV.foreach(params[:file], headers: true) do |row|
      customers << row.to_h
    end
    Customer.import(customers)
    redirect_to admin_path, notice: "Customers have been imported."
  end

  # POST /customers/import_reg
  def import_reg
    CSV.foreach(params[:file], headers: true) do |row|
      puts row
      @customer = Customer.find_by customer_number: row["customer_number"]
      @customer.update row.to_h
    end
    redirect_to admin_path, notice: "Customers have been updated."
  end

  # GET /customers/export_attendance
  def export_attendance
      @customers = Customer.filter_by_checked_in(true)
      respond_to do |format|
        format.html
        format.csv { send_data @customers.to_csv, filename: "customers_checked_in-#{Date.today}.csv" }
      end
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to admin_url, notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    if turbo_frame_request?
      if @customer.update(customer_params)
        @customers = @customer
        render partial: "customer_saved", locals: { customers: @customers }
      end
    else
      respond_to do |format|
        if @customer.update(customer_params)
          format.html { redirect_to customer_url(@customer), notice: "Customer was successfully updated." }
          format.json { render :show, status: :ok, location: @customer }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @customer.errors, status: :unprocessable_entity }
        end
      end
    end
    ActionCable.server.broadcast('customer_channel', {dinner_delta: dinner_delta, checked_in_count: checked_in_count, attendee_count: attendee_count})
    ActionCable.server.broadcast('admin_channel', {stat_rsvp: total_rsvp, stat_checked_in: total_checkins, stat_walk_ins: total_walkins, stat_percentage: checked_in_percentage, rc_cn: @customer.customer_number, rc_name: @customer.name, rc_add: @customer.phys_address, rc_dc: @customer.actual_dinner_count, rc_walkin: if @customer.registered_at_event then "Yes" else "No" end})
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:customer_number, :name, :phone_number, :search, :address, :file, :checked_in, :registered, :registered_at_event, :dinner_count, :phys_address, :co, :actual_dinner_count, :empdir, :member_number, :attendees)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class="col-4 gy-2" id="<%= dom_id customer %>">
  <div class="card">
    <h5 class="card-header"><%= customer.name.titleize %><% if customer.is_employee %> - Employee<% end %><% if customer.is_director %> - Director<% end %><% if customer.is_vip %> - VIP<% end %>
      <% if current_admin %>
        <%= link_to edit_customer_path(customer), data: { turbo: false } do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-pencil-square float-end" viewBox="0 0 16 16">
            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
          </svg>
        <% end %>
      <% end %>
    </h5>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <% if customer.registered %><span class="badge bg-success">RSVP</span><% else %><span class="badge bg-secondary">No RSVP</span><% end %>
          <% if customer.checked_in %><span class="badge bg-success">Checked-In</span><% end %>
          <% if customer.voted %><span class="badge bg-info text-dark">Voted</span><% end %>
        </li>
        <li class="list-group-item">
          <b>Mailing Address:</b> <%= customer.address.titleize %><br>
          <b>Physical Address:</b> <%= customer.phys_address.titleize %><br>
          <b>Phone Number:</b> <%= number_to_phone(customer.phone_number, area_code: true) %><br>
          <b>Account Number:</b> <%= customer.customer_number %><br>
          <b>Member Number:</b> <%= customer.member_number %><br>
          <% if customer.checked_in %>
            <b>Meal Count:</b> <%= customer.actual_dinner_count %>
          <% end %>
        </li>
        <% if !customer.checked_in %>
          <li class="list-group-item">
            <%= form_with(model: customer, data: { turbo_frame: "customers" }) do |form| %>
              <%= form.hidden_field :checked_in, value: 1 %>
              <% if customer.registered %>
                <div class="form-group trackables">
		              <div class="input-group">
                    <%= form.number_field :actual_dinner_count, class:"form-control", :required => true, value: customer.dinner_count %>
                    <span class="input-group-text">Meal Tickets</span>
                  </div>
                  <br>
                  <div class="input-group">
                    <%= form.number_field :attendees, class:"form-control attendees", :required => true, value: customer.dinner_count %>
                    <span class="input-group-text">Attendees</span>
                  </div>
                </div>
                <br>
                <div class="d-grid">
                  <%= form.submit "Check-In", class:"btn btn-primary" %>
                </div>
              <% else %>
                <%= form.hidden_field :registered_at_event, value: 1 %>
                <div class="form-group trackables">
                  <div class="input-group">
                    <%= form.number_field :actual_dinner_count, class:"form-control", :required => true %>
                    <span class="input-group-text">Meal Tickets</span>
                  </div>
                  <br>
                  <div class="input-group">
                    <%= form.number_field :attendees, class:"form-control attendees", :required => true %>
                    <span class="input-group-text">Attendees</span>
                  </div>
                </div>
                <br>
                <div class="d-grid">
                  <%= form.submit "Register & Check-In", class:"btn btn-primary" %>
                </div>
              <% end %>
            <% end %>
          </li>
        <% end %>
    </ul>
  </div>
</div>

app/views/customers/_customer_saved.html.erb
<%= turbo_frame_tag "customers" do %>
  <div class="clearfix">
	<br><br>
    <div class="row g-5 clearfix">
      <% if @customers %>
        <%= render customers %>
      <% end %>
    </div>
  </div>
  <br>
  <br>
  <br>
  <script>
    document.getElementById("search").value = '';
    document.getElementById("search").select();
  </script>
<% end %>

app/views/customers/_customers.html.erb
<%= turbo_frame_tag "customers" do %>
  <div class="clearfix">
	<br><br>
    <div class="row g-5 clearfix">
      <% if @customers %>
        <%= render customers %>
      <% end %>
    </div>
  </div>
  <br>
  <br>
  <br>
  <script>

    function f(event){
      var dc = event.currentTarget;
      var parent = dc.closest(".trackables");
      var att = parent.querySelector('.attendees');
      att.value = dc.value;
    }
    document.querySelectorAll("[id^='customer_actual_dinner_count']").forEach(el => el.addEventListener('change', f));
  </script>
<% end %>

app/views/customers/_customertable.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Customer Number</th>
      <th scope="col">Name</th>
      <th scope="col">Address</th>
      <th scope="col">Physical Address</th>
      <th scope="col" colspan="3">Status</th>
      <th scope="col">Links</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <% if customer.registered %><tr class="table-success"><% else %><tr class="table-warning"><% end %>
          <td><%= customer.customer_number %></td>
          <td><%= customer.name %></td>
          <td><%= customer.address %></td>
          <td><%= customer.phys_address %></td>
          <td><% if customer.registered %><span class="badge bg-success">RSVP</span><% else %><span class="badge bg-secondary">No RSVP</span><% end %></td>
          <td><% if customer.voted %><span class="badge bg-success">Voted</span><% else %><span class="badge bg-secondary">Not Voted</span><% end %></td>
          <td><% if customer.checked_in %> <span class="badge bg-success">Checked-In</span><% end %></td>
          <td><%= link_to "View", customer_path(customer), class:"badge bg-info" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div class="row">
      <div class="col-12">
        <div class="card p-3">
          <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>
          <ul>
            <% customer.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row justify-content-center">
    <div class="col-9">
      <div class="card p-3">
      <div class="row">
        <div class="col-6">
          <%= form.label :customer_number, class:"form-label" %>
          <%= form.text_field :customer_number, class:"form-control" %>
        </div>
        <div class="col-6">
          <%= form.label :name, class:"form-label" %>
          <%= form.text_field :name, class:"form-control" %>
        </div>
        <div class="col-6">
          <%= form.label "CO", class:"form-label" %>
          <%= form.text_field :co, class:"form-control" %>
        </div>
        <div class="col-6">
          <%= form.label :phone_number, class:"form-label" %>
          <%= form.text_field :phone_number, class:"form-control" %>
        </div>
        <div class="col-6">
          <%= form.label "Mailing Address", class:"form-label" %>
          <%= form.text_field :address, class:"form-control" %>
        </div>
        <div class="col-6">
          <%= form.label "Physical Address", class:"form-label" %>
          <%= form.text_field :phys_address, class:"form-control" %>
        </div>
        <div class="col-6">
          <label class="form-label">Employee / Director:</label>
          <%= form.select(:empdir, [['',nil],['Employee','E'],['Director','D'],['VIP','V']],{}, { :class => 'form-control'}) %>
        </div>
        <div class="col-6">
          <%= form.label "Registered Dinner Count", class:"form-label" %>
          <%= form.number_field :dinner_count, class:"form-control" %>
        </div>
        <div class="col-6">
          <%= form.label "Actual Dinner Count", class:"form-label" %>
          <%= form.number_field :actual_dinner_count, class:"form-control" %>
        </div>
        <div class="col-12">
              <hr>
        </div>
        <div class="col-6">
          <%= form.check_box :registered, class:"form-check-input" %>
          <%= form.label :registered, class:"form-check-label" %>
        </div>
        <div class="col-6">
          <%= form.check_box :checked_in, class:"form-check-input" %>
          <%= form.label :checked_in, class:"form-check-label" %>
        </div>
        <div class="col-6">
          <%= form.check_box :registered_at_event, class:"form-check-input" %>
          <%= form.label :registered_at_event, class:"form-check-label" %>
        </div>
        <div class="col-12">
          <hr>
        </div>
        <div class="col-12">
          <%= form.submit "Save", class:"btn btn-primary float-end" %>
        </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/customers/_stats.html.erb
<ul class="navbar-nav me-auto mb-2 mb-lg-0">
  <li class="nav-item">
    <a class="nav-link active" href="#">Meal Tickets Remaining: <span id="dinner_delta"><%= dinner_delta %></span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="#">Total Attendees: <span id="attendee_count"><%= attendee_count %></span></a>
  </li>
</ul>

app/views/customers/checked_in.html.erb
<h3 class="display-6">Customers who have Checked-In - (<%= @customers.count %>)</h3>
<div class="row">
    <div class="col-12">
    <%= render "customertable" %>
    </div>
</div>
<br>
<br>
<br>
<br>

app/views/customers/edit.html.erb
<div class="row justify-content-center">
  <div class="col-9">

    <h1>Edit Customer</h1>
    <br>
  </div>
</div>
<%= render "form", customer: @customer %>

<br>
<div class="row justify-content-center">
  <div class="col-9">
    <div>
      <%= link_to "Cancel Editing", @customer, class:"btn btn-secondary" %>
      <%= link_to "View All Customers", customers_path, class:"btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/customers/export_attendance.csv.erb
<% headers = ['Customer Number', 'Full Name', 'Registered at Event', 'Dinner Count'] %>
<%= CSV.generate_line headers %>
<% @customers.each do |customer| %>
  <%= CSV.generate_line([customer.customer_number, customer.co, customer.name, customer.registered_at_event, customer.dinner_count, customer.actual_dinner_count]) %>
<% end %>

app/views/customers/index.html.erb
<div id="customers clearfix">
  <%= render "customertable" %>
</div>
<br>
<br>
<br>
<br>

app/views/customers/lookup.html.erb
<div class="row justify-content-center">
  <div class="col-8">
    <h1 class="display-6 text-center"><%= Setting.event_name %> Check-In</h1>
  </div>
</div>
<br>
<div class="clearfix">
  <div class="row justify-content-center align-items-center">
    <div class="col-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Scan customer's bar code or search by the customer's street number.</h5><br>
          <%= form_with url: "/lookup", method: :get, data: { turbo_frame: "customers" } do |form| %>
            <div class="input-group">
              <%= form.text_field :search, class: "form-control form-control-lg", aria: { describedby: 'search-addon' } %>
              <%= form.submit "Search", class:"btn btn-lg btn-primary", id:"search-addon" %>
            </div>
          <% end %>
        </div>
      </div>
    </div
  </div>
</div>
<%= render "customers", customers: @customers %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/rsvp.html.erb
<h3 class="display-6">Customers who have RSVP'ed but not checked in - (<%= @customers.count %>)</h3>
<div class="row">
    <div class="col-12">
    <%= render "customertable" %>
    </div>
</div>
<br>
<br>
<br>
<br>

app/views/customers/show.html.erb
<%= render @customer %>
<br>
<div>
  <% if current_admin && Setting.delete_enabled %>
    <%= button_to "Delete Customer", @customer, method: :delete, class:"btn btn-danger" %>
  <% end %>
</div>