config/routes.rb
Rails.application.routes.draw do
  # mount ActionCable.server, at: '/cable'
  root 'customers#lookup'

  get 'lookup', to: 'customers#lookup'
  get 'customers/export_attendance', to: 'customers#export_attendance'
  get 'admin', to: 'static_pages#admin'
  get 'dashboard', to: 'static_pages#dashboard'
  get 'setup', to: 'static_pages#setup'

  resources :employees
  resources :customers do
    collection do
      post :import
      post :import_reg
      get :rsvp
      get :checked_in
    end
  end
  get 'reset/check_ins', to: 'actions#reset_check_ins'
  get 'reset/registrations', to: 'actions#reset_registrations'
  get 'reset/database', to: 'actions#reset_database'

  resources :sessions, only: [:new, :create, :destroy]

  resources :settings

  get 'login', to: 'static_pages#home'
  get 'logout', to: 'sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Setting.event_name %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <br>
      <%= yield %>
    </div>

    <nav class="navbar fixed-bottom navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Check-In App v1.2</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <%= render "customers/stats" %>
          <div class="d-flex">
	    <span class="navbar-text px-3">Running on <%= Setting.instance_name.upcase %></span>
            <% if current_employee %>
              <span class="navbar-text px-3">Logged in as <%= current_employee.first_name %></span>
              <%= link_to "Lookup", root_url, class:"btn btn-primary" %>
              <span class="navbar-text px-1"></span>
              <% if current_admin %>
                <%= link_to "Admin", admin_url, class:"btn btn-danger" %>
                <span class="navbar-text px-1"></span>
              <% end %>
              <%= link_to "Log Out", logout_url, class:"btn btn-primary" %>
            <% else %>
              <%= link_to "Login", login_url, class:"btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Setting.event_name %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <br>
      <%= yield %>
    </div>
  </body>
</html>